@dataclasses.dataclass
class program_container:
    inputgraph: rdflib.Graph
    outputgraph: typ.List[rdflib.Graph]
    """all combinations of possible new axioms, generated by this program.
    Must contain the variables from inputgraph to add new axiom to an
    existing node
    """


class rdf_implementation:
    def __init__(self, nodetrans):
        pass

    @classmethod
    def from_rdfprograms(self, programlist):
        for p in programlist:
            pass

        
